dataset:
  name: conll-2000-chunking
  path: ${EP_TESTS_DATA}/tokenized_data/roberta-base/conll-2000-chunking
label: conll-2000-chunking-rb-random-ep-21
loader:
  batchsz: 80
  hf_tokenizer_model_or_loc: roberta-base
  label_2_id: ${EP_TESTS_HOME}/eptests/core/config/dataset-labels/conll-2000-chunking.yml
  max_length: 109
  multi_label: false
  name: one-span
  sampler:
    name: sequential
model:
  classifier:
    hsz: 768
    name: linear
    num_labels: 22
  encoder:
    hf_model_or_loc: Jo1811/roberta-random
    layer_index: -1
    name: default
  probe:
    multi_label: false
    name: one-span
  span_pooler:
    name: mean
  token_pooler:
    name: mean
reporting:
  console:
    module: baseline.reporting
  wandb:
    module: eptests.core.reporting_wandb
train:
  early_stopping_metric: weighted_f1
  epochs: 21
  eta: 0.001
  lr_scheduler_type: warmup_linear
  optim: adamw
  warmup_steps: 4998
  weight_decay: 0.01
