dataset:
  name: ontonotes-const
  path: ${EP_TESTS_DATA}/tokenized_data/bert-base-cased/ontonotes-const
label: ontonotes-const-bertbc-random
loader:
  batchsz: 80
  hf_tokenizer_model_or_loc: bert-base-cased
  label_2_id: ${EP_TESTS_HOME}/eptests/core/config/dataset-labels/ontonotes-const.yml
  max_length: 351
  multi_label: false
  name: one-span
  sampler:
    name: sequential
model:
  classifier:
    hsz: 768
    name: linear
    num_labels: 30
  encoder:
    hf_model_or_loc: Jo1811/bert-random
    layer_index: -1
    name: default
  probe:
    multi_label: false
    name: one-span
  span_pooler:
    name: mean
  token_pooler:
    name: mean
reporting:
  console:
    module: baseline.reporting
  wandb:
    module: eptests.core.reporting_wandb
train:
  early_stopping_metric: acc
  epochs: 3
  eta: 0.001
  lr_scheduler_type: warmup_linear
  optim: adamw
  warmup_steps: 6943
  weight_decay: 0.01
