dataset:
  name: semeval-2010-task8-rel-cls
  path: ${EP_TESTS_DATA}/tokenized_data/roberta-base/semeval-2010-task8-rel-cls
loader:
  batchsz: 80
  hf_tokenizer_model_or_loc: roberta-base
  label_2_id: ${EP_TESTS_HOME}/eptests/core/config/dataset-labels/semeval-2010-task8-rel-cls.yml
  max_length: 116
  multi_label: false
  name: two-span
  sampler:
    name: sequential
model:
  classifier:
    hsz: 768
    name: linear
    num_labels: 19
  encoder:
    name: default
    hf_model_or_loc: roberta-base
    layer_index: -1
  probe:
    multi_label: false
    name: two-span
  span_pooler:
    name: mean
  token_pooler:
    name: mean
reporting:
  console:
    module: baseline.reporting
  wandb:
    module: eptests.core.reporting_wandb
train:
  early_stopping_metric: acc
  epochs: 3
  eta: 0.001
  lr_scheduler_type: warmup_linear
  optim: adamw
  warmup_steps: 27
  weight_decay: 0.01
label: semeval-2010-task8-rel-cls-rb
