dataset:
  name: spr1
  path: ${EP_TESTS_DATA}/tokenized_data/roberta-base/spr1
loader:
  batchsz: 80
  hf_tokenizer_model_or_loc: roberta-base
  label_2_id: ${EP_TESTS_HOME}/eptests/core/config/dataset-labels/spr1.yml
  max_length: 93
  multi_label: true
  name: two-span
  sampler:
    name: sequential
model:
  classifier:
    hsz: 768
    name: mlp
    num_labels: 18
  encoder:
    name: default
    hf_model_or_loc: roberta-base
    layer_index: -1
  probe:
    multi_label: true
    name: two-span
  span_pooler:
    name: mean
  token_pooler:
    name: mean
reporting:
  console:
    module: baseline.reporting
  wandb:
    module: eptests.core.reporting_wandb
train:
  early_stopping_metric: acc
  epochs: 3
  eta: 0.001
  lr_scheduler_type: warmup_linear
  optim: adamw
  warmup_steps: 28
  weight_decay: 0.01
label: spr1-rb-mlp
